import Image from 'next/image';
import styles from './section-gallery.module.css';

export function SectionGallery() {
	return (
		<section className={styles.wrap} id="section-gallery">
			<div className={styles.head}>
				<h2 className={styles.heading}>
					Работы <br />
					наших спикеров
				</h2>
			</div>
			<div className={styles.body}>
				<div className={styles.grid}>
					<div className={styles.line}>
						<Image
							className={styles.image}
							src="/images/posters/poster-2.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-3.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-4.jpg"
							alt=""
							width={192}
							height={270}
						/>
					</div>
					<div className={styles.line}>
						<Image
							className={styles.image}
							src="/images/posters/poster-6.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-7.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-8.jpg"
							alt=""
							width={192}
							height={270}
						/>
					</div>
					<div className={styles.line}>
						<Image
							className={styles.image}
							src="/images/posters/poster-10.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-11.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-12.jpg"
							alt=""
							width={192}
							height={270}
						/>
					</div>
					<div className={styles.line}>
						<Image
							className={styles.image}
							src="/images/posters/poster-14.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-1.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-2.jpg"
							alt=""
							width={192}
							height={270}
						/>
					</div>
					<div className={styles.line}>
						<Image
							className={styles.image}
							src="/images/posters/poster-4.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-5.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-6.jpg"
							alt=""
							width={192}
							height={270}
						/>
					</div>
					<div className={styles.line}>
						<Image
							className={styles.image}
							src="/images/posters/poster-8.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-9.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-10.jpg"
							alt=""
							width={192}
							height={270}
						/>
					</div>
					<div className={styles.line}>
						<Image
							className={styles.image}
							src="/images/posters/poster-12.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-13.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-14.jpg"
							alt=""
							width={192}
							height={270}
						/>
					</div>
				</div>
				<div className={styles.grid}>
					<div className={styles.line}>
						<Image
							className={styles.image}
							src="/images/posters/poster-2.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-3.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-4.jpg"
							alt=""
							width={192}
							height={270}
						/>
					</div>
					<div className={styles.line}>
						<Image
							className={styles.image}
							src="/images/posters/poster-6.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-7.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-8.jpg"
							alt=""
							width={192}
							height={270}
						/>
					</div>
					<div className={styles.line}>
						<Image
							className={styles.image}
							src="/images/posters/poster-10.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-11.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-12.jpg"
							alt=""
							width={192}
							height={270}
						/>
					</div>
					<div className={styles.line}>
						<Image
							className={styles.image}
							src="/images/posters/poster-14.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-1.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-2.jpg"
							alt=""
							width={192}
							height={270}
						/>
					</div>
					<div className={styles.line}>
						<Image
							className={styles.image}
							src="/images/posters/poster-4.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-5.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-6.jpg"
							alt=""
							width={192}
							height={270}
						/>
					</div>
					<div className={styles.line}>
						<Image
							className={styles.image}
							src="/images/posters/poster-8.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-9.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-10.jpg"
							alt=""
							width={192}
							height={270}
						/>
					</div>
					<div className={styles.line}>
						<Image
							className={styles.image}
							src="/images/posters/poster-12.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-13.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-14.jpg"
							alt=""
							width={192}
							height={270}
						/>
					</div>
				</div>
				<div className={styles.grid}>
					<div className={styles.line}>
						<Image
							className={styles.image}
							src="/images/posters/poster-2.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-3.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-4.jpg"
							alt=""
							width={192}
							height={270}
						/>
					</div>
					<div className={styles.line}>
						<Image
							className={styles.image}
							src="/images/posters/poster-6.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-7.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-8.jpg"
							alt=""
							width={192}
							height={270}
						/>
					</div>
					<div className={styles.line}>
						<Image
							className={styles.image}
							src="/images/posters/poster-10.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-11.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-12.jpg"
							alt=""
							width={192}
							height={270}
						/>
					</div>
					<div className={styles.line}>
						<Image
							className={styles.image}
							src="/images/posters/poster-14.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-1.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-2.jpg"
							alt=""
							width={192}
							height={270}
						/>
					</div>
					<div className={styles.line}>
						<Image
							className={styles.image}
							src="/images/posters/poster-4.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-5.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-6.jpg"
							alt=""
							width={192}
							height={270}
						/>
					</div>
					<div className={styles.line}>
						<Image
							className={styles.image}
							src="/images/posters/poster-8.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-9.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-10.jpg"
							alt=""
							width={192}
							height={270}
						/>
					</div>
					<div className={styles.line}>
						<Image
							className={styles.image}
							src="/images/posters/poster-12.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-13.jpg"
							alt=""
							width={192}
							height={270}
						/>
						<Image
							className={styles.image}
							src="/images/posters/poster-14.jpg"
							alt=""
							width={192}
							height={270}
						/>
					</div>
				</div>
			</div>
		</section>
	);
}
