import Image from 'next/image';
import { Button } from '@/ui/button/button';
import styles from './section-hero.module.css';

export function SectionHero() {
	return (
		<section className={styles.wrap} id="section-hero">
			<div className={styles.head}>
				<h1 className={styles.heading}>
					<span className="fw-700">Научись снимать</span> свои истории, как в кино
				</h1>
				<p className={styles.text}>
					Опыт мастеров кино, сторителлинга, блогинга и мобильной съёмки - 
					<span className="fw-600">за 8900 ₽ в год</span>
				</p>
				<Button className={styles.button} href="https://getcourse.ru/">
					Начать обучение
				</Button>
				<p className={styles.note}>*Цена зафиксирована только для beta-доступа до сентября 2024 г.</p>
			</div>
			<div className={styles.body}>
				<div className={styles.anim}>
					<div className={styles.anim__gird}>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-1.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-2.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-3.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-4.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-5.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-6.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-7.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-8.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-9.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-10.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-11.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-12.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-13.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-14.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-1.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-2.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-3.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-4.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
					</div>
					<div className={styles.anim__gird}>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-1.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-2.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-3.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-4.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-5.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-6.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-7.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-8.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-9.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-10.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-11.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-12.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-13.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-14.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-1.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-2.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-3.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-4.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
					</div>
					<div className={styles.anim__gird}>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-1.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-2.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-3.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-4.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-5.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-6.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-7.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-8.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-9.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-10.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-11.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-12.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-13.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-14.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-1.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-2.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-3.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-4.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
					</div>
				</div>
			</div>
		</section>
	);
}
