import Image from 'next/image';
import { Button } from '@/app/_components/button/button';
import styles from './section-hero.module.css';

export function SectionHero() {
	return (
		<section className={styles.wrap} id="section-hero">
			<div className={styles.head}>
				<h1 className={styles.heading}>
					Научись <span className="fw-700">рассказывать</span> свои истории, как <br />
					в кино
				</h1>
				<p className={styles.text}>
					Получи опыт мастеров кино, сторителлинга, блогинга и мобильной съёмки в виде удобных курсов в
					годовой подписке MOSHKA
				</p>
				<Button className={styles.button} href="#section-profit">
					Начать обучение
				</Button>
			</div>
			<div className={styles.body}>
				<div className={styles.anim}>
					<div className={styles.anim__gird}>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-1.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-2.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-3.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-4.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-5.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-6.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-7.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-8.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-9.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-10.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-11.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-12.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-13.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-14.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-1.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-2.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-3.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-4.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
					</div>
					<div className={styles.anim__gird}>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-1.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-2.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-3.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-4.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-5.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-6.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-7.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-8.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-9.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-10.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-11.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-12.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-13.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-14.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-1.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-2.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-3.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-4.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
					</div>
					<div className={styles.anim__gird}>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-1.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-2.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-3.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-4.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-5.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-6.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-7.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-8.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-9.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-10.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-11.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-12.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-13.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-14.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-1.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
						<div className={styles.anim__line}>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-2.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-3.jpg"
								alt=""
								width={124}
								height={176}
							/>
							<Image
								className={styles.anim__img}
								src="/images/posters/poster-4.jpg"
								alt=""
								width={124}
								height={176}
							/>
						</div>
					</div>
				</div>
			</div>
		</section>
	);
}
